### ISSUE TITLE
modules\field_type_file delete_submission_file_standalone busted

### ISSUE THREAD

**Issue by johnbleck3** [formtools/module-form_builder#4]
Form_Builder forms with upload field on the edit page . . . Delete - are you sure - Yes: if you have a session logged into formtools it works - if you're NOT logged into formtools it does not work. The button does nothing, popup just sits there.

**Comment by johnbleck3** [comment]
If I remember correctly, - in hindsight - your intent was to have anyone putting in a form to be logged in one way or another. If that is still the case you can disregard my post, and I would have to come up with a way for the public to fill out these forms without signing in and without the need to delete or figuring out how to mod to accommodate.

**Comment by benkeen** [comment]
No, this is definitely a bug. Form Builder forms should be publicly available - but there _should_ be sessions already running for the user (independent of the FT sessions that an FT user has when logging in). I'll check this out!

**Comment by benkeen** [comment]
I've been looking into this further today and I'm actually going to refactor this and pull the code out of the File Upload module and into the Form Builder module where it belongs. Now the FB code will call the File Upload module behind the scenes, rather than rely on Form Builder-specific code in the Upload module. 

When it's done I'll post again here (hopefully today!), but note it'll require upgrading both the Form Builder + File Upload module. 

Thanks!

**Comment by benkeen** [comment]
Edit! Turns out it didn't require such a drastic change. I've updated the File Upload module + will release a new version of this module now. You'll need to upgrade both, and then (sorry!) to make everything work properly you'll need to **rename your published form(s)**. You can just rename them, then rename them back - the important thing is that the file itself was regenerated to get the latest content.

**Comment by johnbleck3** [comment]
Excellent - just tested and works like a charm. Thanks Ben!
